spring:
  config:
    activate:
      on-profile: prod

transliteration:
  useDummy: false

logging:
  file:
    path: logs
    name: ${logging.file.path}/petistaan.log
  logback:
    rollingpolicy:
      file-name-pattern: ${logging.file.path}/petistaan-%d{yyyy-MM-dd}-%i.log
      max-file-size: 10MB

springdoc:
  api-docs.path: /documentation
  swagger-ui.path: /swagger.html
management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health.show-details: always
  info:
    app:
      name: Petistaan API
      message: Production environment

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/petistaan
    username: root
    password: Kasi@123
  jpa:
    hibernate:
      ddl-auto: none
   
