spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://localhost:3306/petistaan
    username: root
    password: "Kasi@123"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: never

springdoc:
  api-docs:
    path: /documentation
  swagger-ui:
    path: /swagger.html

transliteration:
  useDummy: true

logging:
  file:
    name: logs/Petistaan.log
  logback:
    rollingpolicy:
      file-name-pattern: ""
      max-file-size: 10MB

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: Petistaan API
    message: Pet management system for owners and pets (Dev)
